# Generated by Django 3.2.23 on 2023-12-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_auto_20231212_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('loaned', 'Loaned')], default='available', max_length=11),
        ),
    ]
